#!/usr/bin/env zsh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
USER_NAME="$(id -un)"
SUDOERS_FILE="/etc/sudoers.d/micbridge-codex"
INSTALL_SCRIPT="$ROOT_DIR/scripts/install-driver.sh"
UNINSTALL_SCRIPT="$ROOT_DIR/scripts/uninstall-driver.sh"
SAFE_INSTALL_SCRIPT="$ROOT_DIR/scripts/safe-install-driver.sh"

if [[ ! -x "$INSTALL_SCRIPT" || ! -x "$UNINSTALL_SCRIPT" || ! -x "$SAFE_INSTALL_SCRIPT" ]]; then
  echo "Expected scripts not found or not executable:" >&2
  echo "  $INSTALL_SCRIPT" >&2
  echo "  $UNINSTALL_SCRIPT" >&2
  echo "  $SAFE_INSTALL_SCRIPT" >&2
  exit 1
fi

TMP_FILE="$(mktemp /tmp/micbridge-sudoers.XXXXXX)"
trap 'rm -f "$TMP_FILE"' EXIT

cat > "$TMP_FILE" <<RULES
# MicBridge Codex local development permissions
# Generated by scripts/setup-dev-sudo.sh
$USER_NAME ALL=(root) NOPASSWD: $INSTALL_SCRIPT, $UNINSTALL_SCRIPT
$USER_NAME ALL=(root) NOPASSWD: $SAFE_INSTALL_SCRIPT
RULES

sudo install -m 0440 "$TMP_FILE" "$SUDOERS_FILE"
sudo visudo -cf "$SUDOERS_FILE"

echo "Installed sudoers rule: $SUDOERS_FILE"
echo "Allowed without password:"
echo "  sudo -n $INSTALL_SCRIPT"
echo "  sudo -n $UNINSTALL_SCRIPT"
echo "  sudo -n $SAFE_INSTALL_SCRIPT"
